### PR TITLE
no-jira add welsh to back link

### PR DESCRIPTION
**Pull request by mywyau**

### CODE REVIEW

**Comment by mywyau** [comment]
**Current**  
Screenshot 2023-08-18 at 13 12 42

**Comment by mywyau** [comment]
**Requested Change in PR**
Screenshot 2023-08-18 at 13 14 34

**Comment by Taiwo-AB** [comment]
Changes look good. Can you also update the [scalaVersion](https://github.com/hmrc/tax-history-frontend/blob/main/build.sbt#L8) to 2.13.11 and [scoverage](https://github.com/hmrc/tax-history-frontend/blob/9a04d2625c9f15bb79a4c28cab10bcb9d9d1a44c/project/plugins.sbt#L14) to 2.0.8. There will also be a couple of warnings to add types which should be straightforward. Thanks

Screenshot 2023-08-18 at 14 50 06

**Comment by Taiwo-AB** [comment]
Review comments already addressed [here](https://github.com/hmrc/tax-history-frontend/pull/348)

**Review by Taiwo-AB — APPROVED** [review]

**Pull request merged**
